/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study.StudyFrame;

/**
 *
 * @author LAPTOP
 */
public class Display3 extends javax.swing.JFrame {

    /**
     * Creates new form Display3
     */
    public Display3() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backCompareMode = new javax.swing.JButton();
        compareModeMessenger = new javax.swing.JLabel();
        compareStartButton = new javax.swing.JButton();
        compareComboBox1 = new javax.swing.JComboBox<>();
        comparePanel1 = new javax.swing.JPanel();
        compareComboBox2 = new javax.swing.JComboBox<>();
        comparePanel2 = new javax.swing.JPanel();
        algorithmNameLabel1 = new javax.swing.JLabel();
        algorithmNameLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Display3\n");
        setBackground(new java.awt.Color(50, 50, 50));

        backCompareMode.setBackground(new java.awt.Color(0, 204, 204));
        backCompareMode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backCompareMode.setText("Back");

        compareModeMessenger.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        compareModeMessenger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        compareModeMessenger.setText("Compare Mode");

        compareStartButton.setBackground(new java.awt.Color(0, 204, 204));
        compareStartButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        compareStartButton.setText("Start");

        compareComboBox1.setBackground(new java.awt.Color(0, 204, 204));
        compareComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        compareComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chọn", "Bubble sort", "Insertion sort", "Selection sort", "Quick sort", "Merge sort", "....." }));
        compareComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareComboBox1ActionPerformed(evt);
            }
        });

        comparePanel1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout comparePanel1Layout = new javax.swing.GroupLayout(comparePanel1);
        comparePanel1.setLayout(comparePanel1Layout);
        comparePanel1Layout.setHorizontalGroup(
            comparePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        comparePanel1Layout.setVerticalGroup(
            comparePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        compareComboBox2.setBackground(new java.awt.Color(0, 204, 204));
        compareComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        compareComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chọn", "Bubble sort", "Insertion sort", "Selection sort", "Quick sort", "Merge sort", "....." }));
        compareComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareComboBox2ActionPerformed(evt);
            }
        });

        comparePanel2.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout comparePanel2Layout = new javax.swing.GroupLayout(comparePanel2);
        comparePanel2.setLayout(comparePanel2Layout);
        comparePanel2Layout.setHorizontalGroup(
            comparePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        comparePanel2Layout.setVerticalGroup(
            comparePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 177, Short.MAX_VALUE)
        );

        algorithmNameLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        algorithmNameLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        algorithmNameLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        algorithmNameLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backCompareMode, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(compareComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(113, 113, 113)
                                .addComponent(compareModeMessenger))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(compareComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(algorithmNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 26, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comparePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(algorithmNameLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(96, 96, 96)
                                .addComponent(compareStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comparePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compareModeMessenger, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backCompareMode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compareComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comparePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(algorithmNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(compareComboBox2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comparePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(compareStartButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(algorithmNameLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void compareComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareComboBox2ActionPerformed
        // TODO add your handling code here:
        Object selectedItem = compareComboBox2.getSelectedItem();

        if (selectedItem == null) {
            algorithmNameLabel2.setText("Please select an item");
        } else {
            String selectedText = selectedItem.toString();

            if ("Bubble sort".equals(selectedText)) {
                algorithmNameLabel2.setText("Bubble sort");
            } else if ("Insertion sort".equals(selectedText)) {
                algorithmNameLabel2.setText("Insertion sort");
            } else if ("Selection sort".equals(selectedText)) {
                algorithmNameLabel2.setText("Selection sort");
            } else if ("Quick sort".equals(selectedText)) {
                algorithmNameLabel2.setText("Quick sort");
            } else if ("Merge sort".equals(selectedText)) {
                algorithmNameLabel2.setText("Merge sort");
            } else {
                algorithmNameLabel2.setText("Unknown sort");
            }
        }
    }//GEN-LAST:event_compareComboBox2ActionPerformed

    private void compareComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareComboBox1ActionPerformed
        // TODO add your handling code here:
        Object selectedItem = compareComboBox1.getSelectedItem();

        if (selectedItem == null) {
            algorithmNameLabel1.setText("Please select an item");
        } else {
            String selectedText = selectedItem.toString();

            if ("Bubble sort".equals(selectedText)) {
                algorithmNameLabel1.setText("Bubble sort");
            } else if ("Insertion sort".equals(selectedText)) {
                algorithmNameLabel1.setText("Insertion sort");
            } else if ("Selection sort".equals(selectedText)) {
                algorithmNameLabel1.setText("Selection sort");
            } else if ("Quick sort".equals(selectedText)) {
                algorithmNameLabel1.setText("Quick sort");
            } else if ("Merge sort".equals(selectedText)) {
                algorithmNameLabel1.setText("Merge sort");
            } else {
                algorithmNameLabel1.setText("Unknown sort");
            }
        }
    }//GEN-LAST:event_compareComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algorithmNameLabel1;
    private javax.swing.JLabel algorithmNameLabel2;
    private javax.swing.JButton backCompareMode;
    private javax.swing.JComboBox<String> compareComboBox1;
    private javax.swing.JComboBox<String> compareComboBox2;
    private javax.swing.JLabel compareModeMessenger;
    private javax.swing.JPanel comparePanel1;
    private javax.swing.JPanel comparePanel2;
    private javax.swing.JButton compareStartButton;
    // End of variables declaration//GEN-END:variables
}
