/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study.StudyFrame;

/**
 *
 * @author LAPTOP
 */
public class Display2 extends javax.swing.JFrame {

    /**
     * Creates new form Display2
     */
    public Display2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backSingleMode = new javax.swing.JButton();
        singleModeMessenger = new javax.swing.JLabel();
        singleComboBox = new javax.swing.JComboBox<>();
        singleStartButton = new javax.swing.JButton();
        singleSortPanel = new javax.swing.JPanel();
        algorithmNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Display2\n");
        setBackground(new java.awt.Color(51, 51, 51));
        setSize(new java.awt.Dimension(800, 500));

        backSingleMode.setBackground(new java.awt.Color(0, 204, 204));
        backSingleMode.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backSingleMode.setText("Back");

        singleModeMessenger.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        singleModeMessenger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        singleModeMessenger.setText("Single mode");

        singleComboBox.setBackground(new java.awt.Color(0, 204, 204));
        singleComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        singleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "chọn", "Bubble sort", "Insertion sort", "Selection sort", "Quick sort", "Merge sort", "....." }));
        singleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleComboBoxActionPerformed(evt);
            }
        });

        singleStartButton.setBackground(new java.awt.Color(0, 204, 204));
        singleStartButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        singleStartButton.setText("Start");

        singleSortPanel.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout singleSortPanelLayout = new javax.swing.GroupLayout(singleSortPanel);
        singleSortPanel.setLayout(singleSortPanelLayout);
        singleSortPanelLayout.setHorizontalGroup(
            singleSortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );
        singleSortPanelLayout.setVerticalGroup(
            singleSortPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        algorithmNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        algorithmNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        algorithmNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backSingleMode, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(singleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115)
                        .addComponent(singleModeMessenger, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(singleSortPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(algorithmNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144)
                                .addComponent(singleStartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backSingleMode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(singleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(singleModeMessenger, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(singleSortPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(singleStartButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(algorithmNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void singleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleComboBoxActionPerformed
        // TODO add your handling code here:
        Object selectedItem = singleComboBox.getSelectedItem();

        if (selectedItem == null) {
            algorithmNameLabel.setText("Please select an item");
        } else {
            String selectedText = selectedItem.toString();

            if ("Bubble sort".equals(selectedText)) {
                algorithmNameLabel.setText("Bubble sort");
            } else if ("Insertion sort".equals(selectedText)) {
                algorithmNameLabel.setText("Insertion sort");
            } else if ("Selection sort".equals(selectedText)) {
                algorithmNameLabel.setText("Selection sort");
            } else if ("Quick sort".equals(selectedText)) {
                algorithmNameLabel.setText("Quick sort");
            } else if ("Merge sort".equals(selectedText)) {
                algorithmNameLabel.setText("Merge sort");
            } else {
                algorithmNameLabel.setText("Unknown sort");
            }
        }
    }//GEN-LAST:event_singleComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel algorithmNameLabel;
    private javax.swing.JButton backSingleMode;
    private javax.swing.JComboBox<String> singleComboBox;
    private javax.swing.JLabel singleModeMessenger;
    private javax.swing.JPanel singleSortPanel;
    private javax.swing.JButton singleStartButton;
    // End of variables declaration//GEN-END:variables
}
